services:
    app:
        build:
            context: .
        env_file:
            - .env
        ports:
            - "8000:8000"
        command: >
           sh -c "chown -R my_user:my_user_group /files/media /files/static &&
                  python manage.py wait_for_db && 
                  python manage.py makemigrations && 
                  python manage.py migrate && 
                  python manage.py collectstatic --noinput &&
                  python manage.py runserver 0.0.0.0:8000"
        volumes:
          - ./:/app
          - my_media:/files/media
          - my_static:/files/static
        depends_on:
           - db

    db:
        image: postgres:17-alpine3.22
        restart: always
        env_file:
          - .env
        ports:
           - "5433:5432"
        volumes:
          - my_db:/var/lib/postgresql/data

volumes:
  my_db:
  my_media:
  my_static:
